name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install -r zi_v_80/requirements.txt
      - run: python -m py_compile zi_v_80/app.py zi_v_80/core/*.py zi_v_80/routers/*.py zi_v_80/modules/*.py
